name: untitled7
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  on_audio_query: ^2.9.0
  audioplayers: ^5.1.0
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  permission_handler: ^10.4.3
  google_fonts: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/musics/
